name = "steganography-app"
main = "workers-site/index.js"
compatibility_date = "2025-09-16"

[site]
bucket = "./" # 静态资源目录

# 开发环境配置
[env.dev]
workers_dev = true

# 生产环境配置
[env.production]
workers_dev = true
# 如果有自定义域名，可以取消下面两行的注释并填写
# route = "your-domain.com/*"
# zone_id = ""